set $browser brave

set $chatgpt_url "https://chatgpt.com/"
set $pw_url "https://www.pw.live/study/batches/lakshya-jee-2-0-2025-073029/batch-overview?came_from=my-batches&activeSection=All%20Classes"
set $notion_url "https://www.notion.so/"
set $figma_url "https://www.figma.com/"
set $telegram_url "https://web.telegram.org/k/"

bindsym $mod+Return exec --no-startup-id kitty

mode "application" {
  bindsym b exec --no-startup-id $browser --new-window; mode "default"
  
  # return to normal
  bindsym Return mode "default"
  bindsym Escape mode "default"
}

bindsym $mod+a mode "application"
