name: Export Neovim Config

on:
  push:
    paths:
      - ".github/**"
      - "configurations/nvim.nix"
      - "modules/neovim/**"
      - "modules/stylix.nix"
      - "flake.nix"
      - "flake.lock"

  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dbus

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enable cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build Home Manager config
        run: |
          nix build .#homeConfigurations.nvim.activationPackage

      - name: Generate config
        run: |
          mkdir -p /tmp/nvim

          HOME=/tmp/nvim \
          USER=nvim \
          ./result/activate

      - name: Collect config
        run: |
          mkdir export
          cp -r /tmp/nvim/.config/nvim export/

      - name: Checkout destination repository
        uses: actions/checkout@v4
        with:
          repository: nandesh-dev/neovim-config
          token: ${{ secrets.NVIM_REPO_TOKEN }}
          path: target

      - name: Update repository
        run: |
          rm -rf target/*
          cp -r export/nvim target/

          cd target

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update from Nix"
          git push
